### ISSUE TITLE
TCP port encoding

### ISSUE THREAD

**Issue by authguardian** [aboehm/pysyslogclient#1]
Hello,
I am new to writing syslogs from python to remote server running on TCP port. When I try to send the messages the string encoding is doesn't seems to be right. Thank you so much for the wonderful library. I was hoping that you can point me to right direction as the messages prints clearly on UDP port when observed using tcpdump.

Thank you

**Comment by aboehm** [comment]
Which python version do you use?

**Comment by authguardian** [comment]
I am using Python 3.8. Instead of tcpdump i used a script to run as syslog server and used this library to send the message to server and it is working as expected just cant use with tcpdump.
Thank you
